BASE_PAGE = 'https://stellarburgers.nomoreparties.site/'
ENDPOINT_PERSONAL_ACCOUNT_PAGE = 'account/profile'
ENDPOINT_ENTRANCE_PAGE = 'login'
ENDPOINT_RECOVERY_PASSWORD_PAGE = 'forgot-password'
ENDPOINT_RESET_PASSWORD = 'reset-password'
ENDPOINT_ORDER_FEED = 'feed'
REGISTRATION_USER_ENDPOINT = 'api/auth/register'
DELETE_USER_ENDPOINT = 'api/auth/user'
